site_name: LARA Interactive API
theme: readthedocs
site_dir: dist/docs
repo_name: Github
repo_url: https://github.com/concord-consortium/lara-interactive-api
site_url: http://concord-consortium.github.io/lara-interactive-api/
pages:
- LARA Interactive API: 'index.md'
- Shutterbug API: 'shutterbug.md'
- Using iFramePhone: 'using-iframe-phone.md'
- Safari / IE, cookies and iframe redirects: 'safari-cookies-redirects.md'
- About the documentation generator: 'about-mkdocs.md'
