site_name: LARA Interactive API
theme: readthedocs
site_dir: dist/docs
repo_name: Github
repo_url: https://github.com/concord-consortium/lara-interactive-api
site_url: http://concord-consortium.github.io/lara-interactive-api/
pages:
- LARA API: 'index.md'
- About the documentation generator: 'about-mkdocs.md'
